### ISSUE TITLE
Exposed apiKey data in public/index-ar.html

### ISSUE THREAD

**Issue by ismaail** [El-Mehdi-Abdi/coronanews-src#1]
https://github.com/El-Mehdi-Abdi/coronanews-src/blob/master/public/index-ar.html#L12

**Comment by El-Mehdi-Abdi** [comment]
The apiKey essentially just identifies Firebase project on the Google servers. It is not a security risk for someone to know it. In fact, it is necessary for them to know it, in order for them to interact with Firebase project.

**Comment by ismaail** [comment]
OK (closed)
